"""Initial migration

Revision ID: bcbb58e2e725
Revises: 
Create Date: 2021-01-05 00:03:27.807803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcbb58e2e725'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_auto', sa.String(length=128), nullable=False),
    sa.Column('describe', sa.String(length=128), nullable=False),
    sa.Column('rent_price', sa.Float(), nullable=True),
    sa.Column('transmission', sa.Boolean(), nullable=True),
    sa.Column('img_url', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('completion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rent')
    op.drop_table('car')
    # ### end Alembic commands ###
